from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Sequence

from .diff import compare_suite_to_candidate, format_report
from .io import read_json, read_jsonl_records, write_json, write_jsonl, write_text
from .judgments import JUDGMENT_STATUSES, clear_suite_case_judgment, mark_suite_case
from .policy import DEFAULT_FAIL_ON, parse_fail_on, should_fail
from .reports import format_markdown_report
from .replay import replay_suite
from .suite import build_suite


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except ValueError as exc:
        print(f"redline: {exc}", file=sys.stderr)
        return 2


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="redline",
        description="Local-first prompt regression diffs from JSONL logs.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    suite_parser = subparsers.add_parser("suite", help="generate a representative suite")
    suite_parser.add_argument("log", help="baseline JSONL file")
    suite_parser.add_argument("--out", default=".redline/suite.json", help="suite output path")
    suite_parser.add_argument("--input-field", default="prompt", help="JSONL input field")
    suite_parser.add_argument("--output-field", default="response", help="JSONL output field")
    suite_parser.add_argument("--max-cases", type=int, default=42, help="maximum suite cases")
    suite_parser.set_defaults(func=cmd_suite)

    diff_parser = subparsers.add_parser("diff", help="compare candidate JSONL to a suite")
    diff_parser.add_argument("suite", help="suite JSON generated by redline suite")
    diff_parser.add_argument("candidate", help="candidate JSONL file")
    diff_parser.add_argument("--input-field", help="candidate input field; defaults to suite input field")
    diff_parser.add_argument("--output-field", help="candidate output field; defaults to suite output field")
    diff_parser.add_argument("--json", action="store_true", help="print machine-readable JSON")
    diff_parser.add_argument("--out-json", help="write machine-readable JSON report")
    diff_parser.add_argument("--out-md", help="write Markdown report")
    diff_parser.add_argument(
        "--fail-on",
        default=",".join(DEFAULT_FAIL_ON),
        help="comma-separated statuses that produce exit code 1; use 'none' for report-only",
    )
    diff_parser.set_defaults(func=cmd_diff)

    eval_parser = subparsers.add_parser("eval", help="replay a suite with a local command")
    eval_parser.add_argument("suite", help="suite JSON generated by redline suite")
    eval_parser.add_argument(
        "--replay",
        required=True,
        help="command to run for each case; receives prompt on stdin unless argv contains {prompt}",
    )
    eval_parser.add_argument("--timeout", type=float, default=30.0, help="per-case timeout in seconds")
    eval_parser.add_argument("--json", action="store_true", help="print machine-readable JSON")
    eval_parser.add_argument("--out-json", help="write machine-readable JSON report")
    eval_parser.add_argument("--out-md", help="write Markdown report")
    eval_parser.add_argument("--candidate-out", help="write replayed candidate prompt-response JSONL")
    eval_parser.add_argument(
        "--fail-on",
        default=",".join(DEFAULT_FAIL_ON),
        help="comma-separated statuses that produce exit code 1; use 'none' for report-only",
    )
    eval_parser.set_defaults(func=cmd_eval)

    mark_parser = subparsers.add_parser("mark", help="mark a suite case judgment")
    mark_parser.add_argument("suite", help="suite JSON generated by redline suite")
    mark_parser.add_argument("case_id", help="case id to mark")
    mark_parser.add_argument("--status", choices=JUDGMENT_STATUSES, required=True)
    mark_parser.add_argument("--note", default="", help="short reason for the judgment")
    mark_parser.add_argument("--out", help="write updated suite to a new path")
    mark_parser.set_defaults(func=cmd_mark)

    clear_parser = subparsers.add_parser("clear", help="clear a suite case judgment")
    clear_parser.add_argument("suite", help="suite JSON generated by redline suite")
    clear_parser.add_argument("case_id", help="case id to clear")
    clear_parser.add_argument("--out", help="write updated suite to a new path")
    clear_parser.set_defaults(func=cmd_clear)

    return parser


def cmd_suite(args: argparse.Namespace) -> int:
    records = read_jsonl_records(args.log, args.input_field, args.output_field)
    suite = build_suite(
        records,
        source=args.log,
        input_field=args.input_field,
        output_field=args.output_field,
        max_cases=args.max_cases,
    )
    write_json(args.out, suite)
    summary = suite["summary"]
    print(f"Generated {summary['cases']} cases from {summary['records_seen']} records.")
    print(f"Detected {summary['clusters']} behavioral clusters.")
    print(f"Wrote {Path(args.out)}.")
    return 0


def cmd_diff(args: argparse.Namespace) -> int:
    suite = read_json(args.suite)
    input_field = args.input_field or str(suite.get("input_field", "prompt"))
    output_field = args.output_field or str(suite.get("output_field", "response"))
    candidate = read_jsonl_records(args.candidate, input_field, output_field)
    result = compare_suite_to_candidate(suite, candidate)

    return _emit_result(args, result, title="redline diff")


def cmd_eval(args: argparse.Namespace) -> int:
    suite = read_json(args.suite)
    replay = replay_suite(suite, args.replay, timeout_seconds=args.timeout)
    if args.candidate_out:
        write_jsonl(args.candidate_out, (record.raw for record in replay.records))
    result = compare_suite_to_candidate(suite, replay.records)
    result["replay"] = replay.to_metadata()

    return _emit_result(args, result, title="redline eval")


def cmd_mark(args: argparse.Namespace) -> int:
    suite = read_json(args.suite)
    mark_suite_case(suite, args.case_id, status=args.status, note=args.note)
    output = args.out or args.suite
    write_json(output, suite)
    print(f"Marked {args.case_id} as {args.status} in {Path(output)}.")
    return 0


def cmd_clear(args: argparse.Namespace) -> int:
    suite = read_json(args.suite)
    removed = clear_suite_case_judgment(suite, args.case_id)
    output = args.out or args.suite
    write_json(output, suite)
    if removed:
        print(f"Cleared judgment for {args.case_id} in {Path(output)}.")
    else:
        print(f"No judgment found for {args.case_id} in {Path(output)}.")
    return 0


def _emit_result(args: argparse.Namespace, result: dict[str, object], *, title: str) -> int:
    fail_on = parse_fail_on(args.fail_on)
    if args.out_json:
        write_json(args.out_json, result)
    if args.out_md:
        write_text(args.out_md, format_markdown_report(result, title=title))

    if args.json:
        print(json.dumps(result, indent=2, sort_keys=True))
    else:
        print(format_report(result, title=title), end="")

    return 1 if should_fail(result, fail_on) else 0
